### ISSUE TITLE
To-do before the launch

### ISSUE THREAD

**Issue by EST-Karol** [Energy-Saving-Trust/Design-System#16]
Review and add content to the following pages:
For detailed task breakdown: https://app.clickup.com/20604774/v/l/kmtv6-97632 

**Guidelines:**
- [ ] Design Principles 
- [ ] Accessibility
- [x] Colour
- [ ] Typography

**Component documentation:**
- [ ] [Accordion](https://design-system-test-preview.pages.dev/components/accordion.html)
- [ ] [Alerts](https://design-system-test-preview.pages.dev/components/alerts.html)
- [ ] [Back to Top](https://design-system-test-preview.pages.dev/components/back-to-top.html)
- [ ] [Breadcrumbs](https://design-system-test-preview.pages.dev/components/breadcrumbs.html)
- [ ] [Bullet Point Lists](https://design-system-test-preview.pages.dev/components/bullets.html)
- [ ] [Buttons](https://design-system-test-preview.pages.dev/components/buttons.html)
- [ ] Cards
- [ ] [Checkbox & Radio](https://design-system-test-preview.pages.dev/components/checkbox-radio.html)
- [ ] [Hint](https://design-system-test-preview.pages.dev/components/hint.html)
- [ ] [Input](https://design-system-test-preview.pages.dev/components/input.html)
- [ ] Links
- [ ] Modal
- [ ] Metric
- [ ] Progress indicators
- [ ] Quotes
- [ ] [Select](https://design-system-test-preview.pages.dev/components/select.html)
- [ ] Table of contents
- [ ] Table
- [ ] [Textarea](https://design-system-test-preview.pages.dev/components/textarea.html)
- [ ] Validation

**Pattern documentation:**
- [ ] Addresses/postcode finder
- [ ] Cookie notification
- [ ] Date picker
- [ ] Filter
- [ ] Footer
- [ ] Header
- [ ] Hero
- [ ] Loading indicator
- [ ] Log in / Sign up
- [ ] Menu
- [ ] Pagination
- [ ] Search

**Other**
- [ ] Distributable code package

____________________________________

**Tasks**
- [ ] Review of the copy for House style compliance
- [ ] Comms for announcing the Design System

**Testing**
- [ ] Internal user testing of patterns
- [ ] External user testing of patterns
- [ ] Accessibility audit (internal)
- [ ] Accessibility audit (external agency)
- [ ] Code testing

**Stakeholder sign-off**
- [ ] Angela
- [ ] Linda
- [ ] Matt

**Review**
- [ ] Mark & Wayne
- [ ] Louise 
- [ ] Euan
- [ ] Product & Design team
